server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "User Microservice"
    description: "Otablo Application - MS User"
    version: "1.0.0"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/otablodb
    username: otablo_user
    password: {cipher}aaf05907c00ffb79fa3716975c47c7e3b2d843cd7dc732ee814833d8182d579b29ca374c75334a212dcb5522f85fcae7
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: DEBUG